package com.spotify.protoman.validation;

public enum ViolationType {
  STYLE_GUIDE_VIOLATION,
  BEST_PRACTICE_VIOLATION,
  GENERATED_SOURCE_CODE_INCOMPATIBILITY_VIOLATION,
  WIRE_INCOMPATIBILITY_VIOLATION,
  FIELD_MASK_INCOMPATIBILITY,
  JSON_ENCODING_INCOMPATIBILITY
}
