// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

/*
Package registry is a generated protocol buffer package.

It is generated from these files:
	registry.proto

It has these top-level messages:
	PublishSchemaRequest
	PublishSchemaResponse
	Error
	ProtoFile
	ValidationViolation
	FilePosition
	PublishedPackage
	SchemaVersion
	GetSchemaRequest
	GetSchemaResponse
*/
package registry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishSchemaRequest struct {
	ProtoFile []*ProtoFile `protobuf:"bytes,1,rep,name=proto_file,json=protoFile" json:"proto_file,omitempty"`
	DryRun    bool         `protobuf:"varint,2,opt,name=dry_run,json=dryRun" json:"dry_run,omitempty"`
	Force     bool         `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
}

func (m *PublishSchemaRequest) Reset()                    { *m = PublishSchemaRequest{} }
func (m *PublishSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishSchemaRequest) ProtoMessage()               {}
func (*PublishSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PublishSchemaRequest) GetProtoFile() []*ProtoFile {
	if m != nil {
		return m.ProtoFile
	}
	return nil
}

func (m *PublishSchemaRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *PublishSchemaRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type PublishSchemaResponse struct {
	PublishedPackage []*PublishedPackage    `protobuf:"bytes,1,rep,name=published_package,json=publishedPackage" json:"published_package,omitempty"`
	Violation        []*ValidationViolation `protobuf:"bytes,2,rep,name=violation" json:"violation,omitempty"`
	Error            *Error                 `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *PublishSchemaResponse) Reset()                    { *m = PublishSchemaResponse{} }
func (m *PublishSchemaResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishSchemaResponse) ProtoMessage()               {}
func (*PublishSchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PublishSchemaResponse) GetPublishedPackage() []*PublishedPackage {
	if m != nil {
		return m.PublishedPackage
	}
	return nil
}

func (m *PublishSchemaResponse) GetViolation() []*ValidationViolation {
	if m != nil {
		return m.Violation
	}
	return nil
}

func (m *PublishSchemaResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProtoFile struct {
	Path    string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *ProtoFile) Reset()                    { *m = ProtoFile{} }
func (m *ProtoFile) String() string            { return proto.CompactTextString(m) }
func (*ProtoFile) ProtoMessage()               {}
func (*ProtoFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ProtoFile) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ValidationViolation struct {
	Description string        `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Fatal       bool          `protobuf:"varint,2,opt,name=fatal" json:"fatal,omitempty"`
	Current     *FilePosition `protobuf:"bytes,3,opt,name=current" json:"current,omitempty"`
	Candidate   *FilePosition `protobuf:"bytes,4,opt,name=candidate" json:"candidate,omitempty"`
}

func (m *ValidationViolation) Reset()                    { *m = ValidationViolation{} }
func (m *ValidationViolation) String() string            { return proto.CompactTextString(m) }
func (*ValidationViolation) ProtoMessage()               {}
func (*ValidationViolation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ValidationViolation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ValidationViolation) GetFatal() bool {
	if m != nil {
		return m.Fatal
	}
	return false
}

func (m *ValidationViolation) GetCurrent() *FilePosition {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *ValidationViolation) GetCandidate() *FilePosition {
	if m != nil {
		return m.Candidate
	}
	return nil
}

type FilePosition struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Line   int32  `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	Column int32  `protobuf:"varint,3,opt,name=column" json:"column,omitempty"`
}

func (m *FilePosition) Reset()                    { *m = FilePosition{} }
func (m *FilePosition) String() string            { return proto.CompactTextString(m) }
func (*FilePosition) ProtoMessage()               {}
func (*FilePosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FilePosition) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FilePosition) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *FilePosition) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type PublishedPackage struct {
	Package     string         `protobuf:"bytes,1,opt,name=package" json:"package,omitempty"`
	PrevVersion *SchemaVersion `protobuf:"bytes,2,opt,name=prev_version,json=prevVersion" json:"prev_version,omitempty"`
	Version     *SchemaVersion `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *PublishedPackage) Reset()                    { *m = PublishedPackage{} }
func (m *PublishedPackage) String() string            { return proto.CompactTextString(m) }
func (*PublishedPackage) ProtoMessage()               {}
func (*PublishedPackage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PublishedPackage) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *PublishedPackage) GetPrevVersion() *SchemaVersion {
	if m != nil {
		return m.PrevVersion
	}
	return nil
}

func (m *PublishedPackage) GetVersion() *SchemaVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

type SchemaVersion struct {
	Major string `protobuf:"bytes,1,opt,name=major" json:"major,omitempty"`
	Minor int32  `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch int32  `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
}

func (m *SchemaVersion) Reset()                    { *m = SchemaVersion{} }
func (m *SchemaVersion) String() string            { return proto.CompactTextString(m) }
func (*SchemaVersion) ProtoMessage()               {}
func (*SchemaVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SchemaVersion) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *SchemaVersion) GetMinor() int32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *SchemaVersion) GetPatch() int32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

type GetSchemaRequest struct {
	Request []*GetSchemaRequest_RequestedPackage `protobuf:"bytes,1,rep,name=request" json:"request,omitempty"`
}

func (m *GetSchemaRequest) Reset()                    { *m = GetSchemaRequest{} }
func (m *GetSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSchemaRequest) ProtoMessage()               {}
func (*GetSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetSchemaRequest) GetRequest() []*GetSchemaRequest_RequestedPackage {
	if m != nil {
		return m.Request
	}
	return nil
}

type GetSchemaRequest_RequestedPackage struct {
	Package string `protobuf:"bytes,1,opt,name=package" json:"package,omitempty"`
}

func (m *GetSchemaRequest_RequestedPackage) Reset()         { *m = GetSchemaRequest_RequestedPackage{} }
func (m *GetSchemaRequest_RequestedPackage) String() string { return proto.CompactTextString(m) }
func (*GetSchemaRequest_RequestedPackage) ProtoMessage()    {}
func (*GetSchemaRequest_RequestedPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *GetSchemaRequest_RequestedPackage) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

type GetSchemaResponse struct {
	ProtoFile []*ProtoFile `protobuf:"bytes,1,rep,name=proto_file,json=protoFile" json:"proto_file,omitempty"`
}

func (m *GetSchemaResponse) Reset()                    { *m = GetSchemaResponse{} }
func (m *GetSchemaResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSchemaResponse) ProtoMessage()               {}
func (*GetSchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetSchemaResponse) GetProtoFile() []*ProtoFile {
	if m != nil {
		return m.ProtoFile
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishSchemaRequest)(nil), "spotify.protoman.PublishSchemaRequest")
	proto.RegisterType((*PublishSchemaResponse)(nil), "spotify.protoman.PublishSchemaResponse")
	proto.RegisterType((*Error)(nil), "spotify.protoman.Error")
	proto.RegisterType((*ProtoFile)(nil), "spotify.protoman.ProtoFile")
	proto.RegisterType((*ValidationViolation)(nil), "spotify.protoman.ValidationViolation")
	proto.RegisterType((*FilePosition)(nil), "spotify.protoman.FilePosition")
	proto.RegisterType((*PublishedPackage)(nil), "spotify.protoman.PublishedPackage")
	proto.RegisterType((*SchemaVersion)(nil), "spotify.protoman.SchemaVersion")
	proto.RegisterType((*GetSchemaRequest)(nil), "spotify.protoman.GetSchemaRequest")
	proto.RegisterType((*GetSchemaRequest_RequestedPackage)(nil), "spotify.protoman.GetSchemaRequest.RequestedPackage")
	proto.RegisterType((*GetSchemaResponse)(nil), "spotify.protoman.GetSchemaResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SchemaRegistry service

type SchemaRegistryClient interface {
	PublishSchema(ctx context.Context, in *PublishSchemaRequest, opts ...grpc.CallOption) (*PublishSchemaResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
}

type schemaRegistryClient struct {
	cc *grpc.ClientConn
}

func NewSchemaRegistryClient(cc *grpc.ClientConn) SchemaRegistryClient {
	return &schemaRegistryClient{cc}
}

func (c *schemaRegistryClient) PublishSchema(ctx context.Context, in *PublishSchemaRequest, opts ...grpc.CallOption) (*PublishSchemaResponse, error) {
	out := new(PublishSchemaResponse)
	err := grpc.Invoke(ctx, "/spotify.protoman.SchemaRegistry/PublishSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaRegistryClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := grpc.Invoke(ctx, "/spotify.protoman.SchemaRegistry/GetSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SchemaRegistry service

type SchemaRegistryServer interface {
	PublishSchema(context.Context, *PublishSchemaRequest) (*PublishSchemaResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
}

func RegisterSchemaRegistryServer(s *grpc.Server, srv SchemaRegistryServer) {
	s.RegisterService(&_SchemaRegistry_serviceDesc, srv)
}

func _SchemaRegistry_PublishSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).PublishSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spotify.protoman.SchemaRegistry/PublishSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).PublishSchema(ctx, req.(*PublishSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaRegistry_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaRegistryServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spotify.protoman.SchemaRegistry/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaRegistryServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchemaRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spotify.protoman.SchemaRegistry",
	HandlerType: (*SchemaRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishSchema",
			Handler:    _SchemaRegistry_PublishSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _SchemaRegistry_GetSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xfe, 0xf9, 0xd7, 0x26, 0xa9, 0x27, 0x6d, 0x95, 0x2e, 0x81, 0x46, 0x41, 0x82, 0xb0, 0x08,
	0xc8, 0x01, 0x72, 0x48, 0x2f, 0x14, 0x71, 0x2a, 0x02, 0x4e, 0xd0, 0xb0, 0x48, 0x39, 0x70, 0x89,
	0x36, 0xf6, 0xa6, 0x59, 0xb0, 0xbd, 0x66, 0x6d, 0x47, 0xca, 0x91, 0x27, 0xe0, 0x41, 0x78, 0x0e,
	0x6e, 0x3c, 0x02, 0x0f, 0x83, 0xf6, 0x5f, 0x93, 0xd8, 0x29, 0xad, 0xc4, 0x29, 0xfb, 0xcd, 0x7c,
	0x33, 0xf9, 0xe6, 0xf3, 0xee, 0xc0, 0xa1, 0x64, 0x17, 0x3c, 0xcb, 0xe5, 0x72, 0x90, 0x4a, 0x91,
	0x0b, 0xd4, 0xca, 0x52, 0x91, 0xf3, 0x99, 0x85, 0x31, 0x4d, 0xf0, 0x37, 0x0f, 0xda, 0xa3, 0x62,
	0x1a, 0xf1, 0x6c, 0xfe, 0x31, 0x98, 0xb3, 0x98, 0x12, 0xf6, 0xb5, 0x60, 0x59, 0x8e, 0x5e, 0x00,
	0x68, 0xd2, 0x64, 0xc6, 0x23, 0xd6, 0xf1, 0x7a, 0x3b, 0xfd, 0xe6, 0xf0, 0xee, 0xa0, 0x5c, 0x3f,
	0x18, 0xa9, 0xc3, 0x1b, 0x1e, 0x31, 0xe2, 0xa7, 0xee, 0x88, 0x8e, 0xa1, 0x11, 0xca, 0xe5, 0x44,
	0x16, 0x49, 0xe7, 0xff, 0x9e, 0xd7, 0xdf, 0x23, 0xf5, 0x50, 0x2e, 0x49, 0x91, 0xa0, 0x36, 0xd4,
	0x66, 0x42, 0x06, 0xac, 0xb3, 0xa3, 0xc3, 0x06, 0xe0, 0xdf, 0x1e, 0xdc, 0x2e, 0x69, 0xc8, 0x52,
	0x91, 0x64, 0x0c, 0x9d, 0xc3, 0x51, 0x6a, 0x12, 0x2c, 0x9c, 0xa4, 0x34, 0xf8, 0x42, 0x2f, 0x9c,
	0x16, 0xbc, 0x45, 0x8b, 0xa3, 0x8e, 0x0c, 0x93, 0xb4, 0xd2, 0x52, 0x04, 0xbd, 0x02, 0x7f, 0xc1,
	0x45, 0x44, 0x73, 0x2e, 0x94, 0x36, 0xd5, 0xe8, 0x51, 0xb5, 0xd1, 0x98, 0x46, 0x3c, 0xd4, 0x9c,
	0xb1, 0x23, 0x93, 0x55, 0x1d, 0x7a, 0x06, 0x35, 0x26, 0xa5, 0x90, 0x7a, 0x8a, 0xe6, 0xf0, 0xb8,
	0xda, 0xe0, 0xb5, 0x4a, 0x13, 0xc3, 0xc2, 0x0f, 0xa0, 0xa6, 0x31, 0xea, 0x40, 0x23, 0x66, 0x59,
	0x66, 0x66, 0xf0, 0xfa, 0x3e, 0x71, 0x10, 0x9f, 0x82, 0x7f, 0x69, 0x24, 0x42, 0xb0, 0x9b, 0xd2,
	0x7c, 0x6e, 0x39, 0xfa, 0xac, 0x4a, 0x03, 0x91, 0xe4, 0x2c, 0xc9, 0xb5, 0xa3, 0x3e, 0x71, 0x10,
	0xff, 0xf4, 0xe0, 0xd6, 0x16, 0xbd, 0xa8, 0x07, 0xcd, 0x90, 0x65, 0x81, 0xe4, 0xa9, 0x9e, 0xd5,
	0x34, 0x5b, 0x0f, 0xe9, 0x8f, 0x41, 0x73, 0x1a, 0xd9, 0x6f, 0x64, 0x00, 0x7a, 0x0e, 0x8d, 0xa0,
	0x90, 0x52, 0xfd, 0x93, 0x19, 0xef, 0x5e, 0x75, 0x3c, 0x25, 0x73, 0x24, 0x32, 0xae, 0x8d, 0x71,
	0x74, 0xf4, 0x12, 0xfc, 0x80, 0x26, 0xa1, 0x52, 0xc2, 0x3a, 0xbb, 0x37, 0xaa, 0x5d, 0x15, 0xe0,
	0xf7, 0xb0, 0xbf, 0x9e, 0xda, 0xea, 0x02, 0x82, 0xdd, 0x88, 0x27, 0x4c, 0x0b, 0xae, 0x11, 0x7d,
	0x46, 0x77, 0xa0, 0x1e, 0x88, 0xa8, 0x88, 0x13, 0x2d, 0xb7, 0x46, 0x2c, 0xc2, 0x3f, 0x3c, 0x68,
	0x95, 0x2f, 0x84, 0xb2, 0x71, 0x75, 0x8b, 0xb4, 0x8d, 0x16, 0xa2, 0x33, 0xd8, 0x4f, 0x25, 0x5b,
	0x4c, 0x16, 0x4c, 0x66, 0xe6, 0x6e, 0x28, 0xfd, 0xf7, 0xab, 0xfa, 0xcd, 0x0d, 0x1d, 0x1b, 0x1a,
	0x69, 0xaa, 0x22, 0x0b, 0xd0, 0x29, 0x34, 0x5c, 0xf9, 0xce, 0xcd, 0xca, 0x1d, 0x1f, 0x7f, 0x80,
	0x83, 0x8d, 0x8c, 0xfa, 0x38, 0x31, 0xfd, 0x2c, 0xa4, 0xd5, 0x69, 0x80, 0x8e, 0xf2, 0x44, 0x48,
	0xeb, 0x80, 0x01, 0x2a, 0x9a, 0xd2, 0x3c, 0x98, 0x5b, 0x07, 0x0c, 0xc0, 0xdf, 0x3d, 0x68, 0xbd,
	0x65, 0xf9, 0xe6, 0xab, 0x7e, 0x07, 0x0d, 0x69, 0x8e, 0xf6, 0x19, 0x9d, 0x54, 0x25, 0x96, 0x8b,
	0x06, 0xf6, 0x77, 0xf5, 0xae, 0x5c, 0x8f, 0xee, 0x53, 0x68, 0x95, 0x93, 0x57, 0x7b, 0x8c, 0xcf,
	0xe1, 0x68, 0xad, 0xb7, 0x7d, 0xe2, 0xff, 0xb0, 0x67, 0x86, 0xbf, 0x3c, 0x38, 0x74, 0xed, 0xcc,
	0x9e, 0x43, 0x53, 0x38, 0xd8, 0x58, 0x25, 0xe8, 0xf1, 0x95, 0x7b, 0x62, 0x63, 0xc8, 0xee, 0x93,
	0x6b, 0x79, 0x46, 0x30, 0xfe, 0x0f, 0x8d, 0xc1, 0xbf, 0x9c, 0x03, 0xe1, 0xeb, 0x0d, 0xec, 0x3e,
	0xfc, 0x2b, 0xc7, 0xf5, 0x3d, 0xc3, 0xd0, 0x0e, 0x44, 0x5c, 0xe1, 0x8e, 0xbc, 0x4f, 0x7b, 0x6e,
	0x8f, 0x4f, 0xeb, 0x3a, 0x7a, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xae, 0x4c, 0x04, 0xda,
	0x05, 0x00, 0x00,
}
